import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { SessionProvider } from "@/components/SessionProvider";
import Login from "@/components/Login";
import Page from '@/app/page';


const roboto = Roboto({
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Khat GPT",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider session={session}>
          {!session ?
          (<Login /> )
        : (
          <Page />
        )}

        </SessionProvider>
        </body>
    </html>
  );
}
